"""check

Revision ID: 4b64e0d79743
Revises: 3eb39601f743
Create Date: 2024-05-04 17:24:39.696811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b64e0d79743'
down_revision = '3eb39601f743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('wallet_id', sa.String(), nullable=False))
    op.alter_column('wallet', 'password',
               existing_type=sa.VARCHAR(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('purchase', 'wallet_id')
    # ### end Alembic commands ###
