"""initial

Revision ID: 618eefa651c7
Revises: 
Create Date: 2024-04-17 23:41:25.894515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618eefa651c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('Еда', 'Одежда', 'Техника', 'Другое', native_enum=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_wallet', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('Пополнение', 'Списание', native_enum=False), nullable=False),
    sa.Column('summ', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_wallet'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('wallet')
    op.drop_table('purchase')
    # ### end Alembic commands ###
