"""check

Revision ID: 693e99da7d06
Revises: aab8e09e36b3
Create Date: 2024-05-08 10:46:52.709753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693e99da7d06'
down_revision = 'aab8e09e36b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Пополнение', 'Списание', 'Возврат товара', native_enum=False),
               existing_nullable=False)
    op.alter_column('wallet', 'password',
               existing_type=sa.VARCHAR(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('operation', 'type',
               existing_type=sa.Enum('Пополнение', 'Списание', 'Возврат товара', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
